const float angularVelocity = 2 * pi / (1); //1 rotation per second
const float linearAcceleration = 1; // (m/s^2)
const float maxLinearVelocity = 1.0f;
const float linearDamping = 0.8f;
const float asteroidHeading = 0.5;
const float asteroidTravelHeading = 30 / 180.0f * pi; //30 degrees in radian fly direction
const float ufoHeading = 0;
const bool enableMomentum = false;
const float gameSpeed = 1;